Mime::Type.register("application/rdf+xml", :rdf)
Mime::Type.register("text/turtle", :ttl)
Mime::Type.register("application/n-triples", :nt)
Mime::Type.register("application/sparql-results+xml", :sparqlxml)
Mime::Type.register("application/sparql-results+json", :sparqljson)